<a href="https://colab.research.google.com/github/ucpcpu/Data-Science/blob/main/Classifiers_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing the libraries
import numpy as np
import pandas  as pd
import matplotlib.pyplot as plt

#importing the datset
dataset=pd.read_csv("/content/Data (1).csv")
print("Dataset(first 5 rows)", dataset.head())
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

#train test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state= 0)

#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

Dataset(first 5 rows)    Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

   Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0            1                3  

#Logistic Regression

In [ ]:
#getting the model and training it
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(x_train, y_train)

#predicting the test results
y_pred = classifier.predict(x_test)

#making the confusion matrix
from sklearn.metrics import accuracy_score, confusion_matrix
y_pred=classifier.predict(x_test)
cm=confusion_matrix(y_test, y_pred)
print(cm)
print(accuracy_score(y_pred, y_test))

[[103   4]
 [  5  59]]
0.9473684210526315


#K-Nearest Neighbours

In [ ]:
#training the model
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=5, metric="minkowski", p=2)
classifier.fit(x,y)

#prediction of test results
y_pred=classifier.predict(x_test)

#confusion matrix and accuracy score
from sklearn.metrics import accuracy_score, confusion_matrix
cm=confusion_matrix(y_pred, y_test)
print(cm)
print(accuracy_score(y_pred, y_test))

[[  0   0]
 [107  64]]
0.3742690058479532


#Support Vector Machine

In [ ]:
#training the model
from sklearn.svm import SVC
classifier=SVC(kernel="linear", random_state=0)
classifier.fit(x_train, y_train)
y_pred=classifier.predict(x_test)

#confusion matrix and accuracy score
from sklearn.metrics import accuracy_score, confusion_matrix
cm=confusion_matrix(y_pred, y_test)
print(cm)
print(accuracy_score(y_pred, y_test))

[[102   5]
 [  5  59]]
0.9415204678362573


#Kernel Trick

In [ ]:
#training the model
from sklearn.svm import SVC
classifier=SVC(kernel="rbf", random_state=0)
classifier.fit(x_train, y_train)
y_pred=classifier.predict(x_test)

#confusion matrix and accuracy score
from sklearn.metrics import accuracy_score, confusion_matrix
cm=confusion_matrix(y_pred, y_test)
print(cm)
print(accuracy_score(y_pred, y_test))

[[102   3]
 [  5  61]]
0.9532163742690059


# Naive Bayes

In [ ]:
#training model
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(x_train, y_train)
y_pred=classifier.predict(x_test)

#confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_pred, y_test))

[[99  2]
 [ 8 62]]
0.9415204678362573


#Decision Tree Classifer

In [ ]:
#training model
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion="entropy", random_state=0)
classifier.fit(x_train, y_train)
y_pred=classifier.predict(x_test)

#confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_pred, y_test))

[[103   3]
 [  4  61]]
0.9590643274853801


#Random Forest Classifier

In [ ]:
#training model
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier(n_estimators=10, criterion="entropy", random_state=0)
classifier.fit(x_train, y_train)
y_pred=classifier.predict(x_test)

#confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_pred, y_test))

[[102   6]
 [  5  58]]
0.935672514619883
