<a href="https://colab.research.google.com/github/ucpcpu/Data-Science/blob/main/Evalution_of_all_regression_models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Multiple Linear Regression

In [ ]:
#importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#importing the dataset
dataset=pd.read_csv("/content/Data.csv")
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

#train test split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

#importing the model and training it
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train, y_train)

#predicting the results
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

from sklearn.metrics import r2_score
k1=r2_score(y_test, y_pred)
print(k1)

[[431.43 431.23]
 [458.56 460.01]
 [462.75 461.14]
 ...
 [469.52 473.26]
 [442.42 438.  ]
 [461.88 463.28]]
0.9325315554761303


#Polynomial Regression

In [ ]:

#importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#importing the dataset
dataset=pd.read_csv("/content/Data.csv")
print(dataset)
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

#Training Linear regression on whole dataset
from sklearn.linear_model import LinearRegression
lin_reg=LinearRegression()
lin_reg.fit(x,y)

#Training Polynomial regression model on whole dataset
from sklearn.preprocessing import PolynomialFeatures
poly_reg=PolynomialFeatures(degree=4)
x_poly=poly_reg.fit_transform(x)
lin_reg_2=LinearRegression()
lin_reg_2.fit(x_poly,y)

y_pred=regressor.predict(x_test)

from sklearn.metrics import r2_score
k2=r2_score(y_test, y_pred)
print(k2)

         AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]
0.9325315554761303


#Support Vector Regression

In [ ]:

#importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#importing the dataset
dataset = pd.read_csv("/content/Data.csv")
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values
print(x)
print(y)
print(y.reshape(len(y),1))
y=y.reshape(len(y),1)

#feature scaling
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
sc_y=StandardScaler()
x=sc_x.fit_transform(x)
y=sc_y.fit_transform(y)
print(x)
print(y)

#training the svr model on whole dataset
from sklearn.svm import SVR
regressor=SVR(kernel="rbf")
regressor.fit(x,y)

y_pred=regressor.predict(x)

from sklearn.metrics import r2_score
k3=r2_score(y,y_pred)
print(k3)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]
[[463.26]
 [444.37]
 [488.56]
 ...
 [429.57]
 [435.74]
 [453.28]]
[[-0.63 -0.99  1.82 -0.01]
 [ 0.74  0.68  1.14 -0.97]
 [-1.95 -1.17 -0.19  1.29]
 ...
 [ 1.57  1.58 -0.06 -2.52]
 [ 0.65  1.19  0.1  -0.75]
 [ 0.26  0.65  0.67 -0.37]]
[[ 0.52]
 [-0.59]
 [ 2.  ]
 ...
 [-1.45]
 [-1.09]
 [-0.06]]


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9462182792854952


#Decision Tree Regressor

In [ ]:

#importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#importing the dataset
dataset=pd.read_csv("/content/Data.csv")
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

#importing and traing the model
from sklearn.tree import DecisionTreeRegressor
regressor=DecisionTreeRegressor(random_state=0)
regressor.fit(x,y)

from sklearn.metrics import r2_score
k4=r2_score(y, regressor.predict(x))
print(k4)

1.0


#Random Forest Regression

In [ ]:

#importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
dataset=pd.read_csv("/content/Data.csv")
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

#importing and traing the model
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=10,random_state=0)
regressor.fit(x,y)

from sklearn.metrics import r2_score
k5=r2_score(y, regressor.predict(x))
print(k5)

0.9926041916640439


In [3]:
print("The Accuracy Scores for the models in respective manner")
print([k1,k2,k3,k4,k5])

The Accuracy Scores for the models in respective manner
